### ISSUE TITLE
Feature: 注册密码长度建议

### ISSUE THREAD

**Issue by zhaogarvie** [zhaogarvie/fbank#8]
**Is your feature request related to a problem? Please describe.**
用户注册的密码只有最小长度的限制，没有最大长度的限制。用户登录的密码长度限制未测试。

**Describe the solution you'd like**
对用户注册密码做最大长度限制，限制密码长度为6-32字符
用户注册邮箱无最小字符限制，应限制为 5-255字符

**Describe alternatives you've considered**

**Additional context**

**Comment by qq2867199593** [comment]
![Uploading image.png…]()
注册接口修改后
